Assets/Scenes/AINewVers - Copy.unity
Assets/Scripts/AI/EnemyAI.cs
Assets/Scripts/ObjectPoolSpawner.cs
Assets/Scripts/SelfDespawn.cs

The EnemyAI now will despawn when falling off the map and will respawn a set distance from the player. I also Added minor changes to SelfDespawn.

Far spawner

---

Assets/Scripts/AI/EnemyAI.cs
Assets/Scripts/PawnScripts/PlayerHealthRegen.cs

Adds a method which will equip a new gun. 
Tom: Please add a new gameobject to the muzzle of the enemy gun so you can hook up the "muzzleLocation"

Equip guns

---

Assets/Art/Cyborgs/Soldier/BlendTreeTest.controller
Assets/Art/Cyborgs/Soldier/models/Cyborg_Soldier@shoot.FBX.meta
Assets/Scripts/AI/CyborgAnimationStateController.cs
Assets/Scripts/AI/EnemyAI.cs

Reworked the CyborgAnimationStateController script and the Animator for the cyborg
Added some new animations

Ai animation rework

---

Assets/Materials/BikeLightEmissive.mat
Assets/Materials/PelletTexture.mat
Assets/Prefabs/Bullets/BasicrifleBulletMat.mat
Assets/Prefabs/Bullets/ShotGunPellet.prefab
Assets/Resources/AiClasses/GruntAI.cs
Assets/Resources/Guns/AkimboRangers.prefab
Assets/Resources/Guns/ShotGun.prefab
Assets/Scripts/AI/Ai.cs
Assets/Scripts/AI/EnemySpawner.cs
Assets/Scripts/Bullets/ShotgunPellet.cs
Assets/Scripts/Bullets/ShotgunPellet.cs.meta
Assets/Scripts/Guns/AIGuns/Shotgun.cs
Assets/Scripts/Player/Rammable.cs

Added Animations to the Ai and rebalanced shotgunner, added prefabs for bullets

Ai clean up

---

Assets/Scripts/AI/HealthPool.cs
Assets/Scripts/Player/BikeScript.cs

The original solutions was broken. It now spawns in front of player

Fixed spawning of health pool

---

Assets/Scenes/TestScene.unity
Assets/Scripts/AI/Ai.cs
Assets/Scripts/AI/EnemyManager.cs
Assets/Scripts/AI/EnemySpawner.cs
Assets/Scripts/AI/ObjectPool.cs

Fixed AI so that effects of death are reset when they next spawn. Also added minor name changes

Ai death bug fix

---

Assets/Scenes/TestScene.unity
Assets/Scripts/Effects/BloodSplatter.cs

Master Currently Has God Mode Enabled and Constant Debug Comment Going.

---

Assets/Scripts/AI/Ai.cs

One of my changes got overwritten and master branch requires a boot in safemode. This change being merged in will override it.

Overwriting previous fix

---

Assets/Art/Cyborgs/Soldier/materials/Cyborg_Soldier_gun_legacy.mat
Assets/Art/Depricated/Cactus/CactusMat.mat
Assets/Art/Material/ScrollingMat.mat
Assets/Art/PostApocalypticCarsPack/Materials/4X Car.mat
Assets/Art/PostApocalypticCarsPack/Materials/AX APp.mat
Assets/Art/PostApocalypticCarsPack/Materials/Apparatus 1.mat
Assets/Art/PostApocalypticCarsPack/Materials/Apparatus.mat
Assets/Art/PostApocalypticCarsPack/Materials/Armor.mat
Assets/Art/PostApocalypticCarsPack/Materials/Oil Tank.mat
Assets/Art/PostApocalypticCarsPack/Materials/Small Truck.mat
Assets/Art/PostApocalypticCarsPack/Materials/Truck Tex.mat
Assets/Art/SpaceShips/Textures(1k)/BaseBlue1k/Materials/T_Blue_Engine_BaseColor.mat
Assets/Art/SpaceShips/Textures(1k)/BaseRed1k/Materials/T_Red_Engine_BaseColor.mat
Assets/Art/SpaceShips/Textures(1k)/BaseYellow1k/Materials/T_Yellow_Engine_BaseColor.mat
Assets/Art/SpaceShips/Textures(1k)/Materials/T_White_Wing_BaseColor.mat
Assets/Materials/New Material.mat
Assets/Materials/PelletTexture.mat
Assets/Materials/WhiteSace.mat
Assets/Prefabs/Bullets/BasicrifleBulletMat.mat
Assets/Prefabs/Bullets/BulletMaterial.mat
Assets/Prefabs/Bullets/TurretBullet/TurretBulletMat.mat
Assets/StreamingAssets/Audio/GeneratedSoundBanks/Windows.meta
Assets/StreamingAssets/Audio/GeneratedSoundBanks/Windows/DecodedBanks.meta
Assets/StreamingAssets/Audio/GeneratedSoundBanks/Windows/DecodedBanks/English(US).meta
Assets/Wwise/LauncherInfo.json.meta
Assets/WwiseSettings.xml

Merging in so we don't have to deal with this on every branch

These files were generated when the project was opened

---

Assets/Scenes/TestScene.unity
Assets/Scripts/Player/BikeMovementComponent.cs

Added controls to the bike movement component to allow for lateral controls

Side force QE controls

---

Assets/Prefabs/Hitboxes.meta
Assets/Prefabs/Hitboxes/HitBoxController.prefab
Assets/Prefabs/Hitboxes/HitBoxController.prefab.meta
Assets/Prefabs/Hitboxes/HitBoxScript.cs
Assets/Prefabs/Hitboxes/HitBoxScript.cs.meta

Created a hitbox prefab that can be dragged onto any object, then you can add as many colliders as you want on the child object of that prefab. The script can then turn on and off all of the colliders via two methods.

Added a hitbox prefab

---

Assets/Resources/EnemyPrefabs/FuckTruck.prefab
Assets/Resources/EnemyPrefabs/FuckTruck.prefab.meta

Added Fuck Truck Prefab 8===D O:

---

Assets/Scenes/TrashBin/Test_Scene.unity
Assets/TrackingScript.cs
ProjectSettings/TagManager.asset

Edited the tracker and bike prefabs to align correctly

Tacker Edit

---

Assets/Prefabs/Guns/Shotty.prefab
Assets/Resources/AiClasses/BikeAI.cs
Assets/Scripts/Enemies/Ai.cs
Assets/Scripts/Enemies/EnemyTurret.cs
Assets/Scripts/Guns/AIGuns/AkimboRangers.cs
Assets/Scripts/Guns/AIGuns/BasicRifle.cs
Assets/Scripts/Guns/AIGuns/Shotgun.cs
Assets/Scripts/Guns/Arsenal.cs
Assets/Scripts/Guns/Gun.cs
Assets/Scripts/Guns/PlayerGuns/DoubleBarrelLMG.cs
Assets/Scripts/Guns/PlayerGuns/LevelledGun.cs
Assets/Scripts/Guns/PlayerGuns/OctoBarrelLMG.cs
Assets/Scripts/Guns/PlayerGuns/Shotty.cs
Assets/Scripts/Guns/PlayerGuns/VulcanV64AutoCannons.cs
Assets/Scripts/Guns/Weapon.cs
Assets/Scripts/Player/BikeMovementComponent.cs
Assets/Scripts/Player/BikeScript.cs
Assets/Scripts/Player/TurretScript.cs
Assets/Scripts/SceneManageMent/ScoreTracker.cs
Assets/Scripts/WorldObjects/WeaponDrop/GunTypes/DefaultGunDrop.cs
Assets/Scripts/WorldObjects/WeaponDrop/GunTypes/OctoLMGDrop.cs
Assets/Scripts/WorldObjects/WeaponDrop/GunTypes/ShottyDrop.cs
Assets/Scripts/WorldObjects/WeaponDrop/GunTypes/VulkanV64AutoCannonsDrop.cs
Assets/Scripts/WorldObjects/WeaponDrop/WeaponDrop.cs
Assets/Scripts/WorldObjects/WeaponDrop/WeaponDropGunType.cs

[Added] Secondary fire method to weapons
[Modified] Arsenal now holds collection of Weapons, not Guns [Added] Shotty has implemented an alt. fire mode
[Known issue]
Shotty wipe is not 360, only fires backwards
Shotty throws Object reference exceptions while shooting

Implemented base primary/alt fire modes

---

Assets/Prefabs/Guns/Arsenal.prefab
Assets/Prefabs/Guns/Shotty.prefab
Assets/Scripts/Bullets/Bullet.cs
Assets/Scripts/Bullets/BulletPool.cs
Assets/Scripts/Bullets/ShottyPellet.cs
Assets/Scripts/Guns/Arsenal.cs
Assets/Scripts/Guns/Gun.cs
Assets/Scripts/Guns/PlayerGuns/OctoBarrelLMG.cs
Assets/Scripts/Guns/PlayerGuns/Shotty.cs

[Added] Shotty pellets grow in size over time
[Fixed] Boost value was 0, meaning bullets weren't applying recoil correctly [Fixed] Guns now properly attach to the arsenal
[Fixed] Increased octolmg bullet pool size to prevent bigboom from going over the limit

Reworked the shotty

---

Assets/Scripts/Effects/HealthFieldManager.cs

I left in a testing input -- my bad!

No longer play effect when spacebar is pressed

---

Assets/Scripts/Audio/Jukebox.cs

Bug Fix: Playing Double Audio At Start

---

Assets/Prefabs/Player/CameraObjects.prefab
Assets/Scripts/Player/CinematicCamera.cs

Top down camera is now locked to be on top of player

Top down camera

---

Assets/Prefabs/Levels.meta
Assets/Prefabs/Levels/InTheirFinalMomentsLevel.prefab
Assets/Prefabs/Levels/InTheirFinalMomentsLevel.prefab.meta
Assets/Scenes/Immutable/TrueScene.unity
Assets/Scripts/Audio/Jukebox.cs
Assets/Scripts/Editor/GameManager.cs
Assets/Scripts/GameManagement/GameLevel.cs
Assets/Scripts/GameManagement/GameLevel.cs.meta
Assets/Scripts/GameManagement/LevelManager.cs
Assets/Scripts/GameManagement/LevelManager.cs.meta
Assets/Scripts/SceneManageMent/WorldGenerator.cs

Created level for InTheirFinalMoments

Implemented Game Level and Level Manager

---

Assets/Scenes/Immutable/MainMenu.unity
Assets/Scripts/SceneManageMent/MainMenu.cs

Basic scene for the Main Menu w/ Options menu. You can toggle between options menu and main menu, you can also load the game scene and exit the application.

Main Menu Template

---

Assets/Scripts/Enemies/DangerLevel.cs
Assets/Scripts/SceneManageMent/Waves/Wave.cs
Assets/Scripts/SceneManageMent/Waves/WaveSequence.cs

Fixed duplicate code bug in wave sequence
Danger levels no longer tick down past current DL threshold

Implemented Danger Level

---

Assets/Prefabs/UI/GameUI.prefab
Assets/Scenes/Immutable/MainMenu.unity
Assets/Scripts/UI/PauseScreen.cs
Assets/Scripts/UI/QuitScreen.cs
Assets/Scripts/UI/QuitScreen.cs.meta

Added quit game confirmations to the main menu and the in-game screen, confirming whether the player wants to exit the game/return to the main menu.

Added quit screen to main menu exit and pause screen return to menu

---

Assets/Prefabs/UI/GameUI.prefab
Assets/Scenes/Immutable/TrueScene.unity
Assets/Scripts/UI/GameplayUI.cs
Assets/Scripts/UI/GameplayUI.cs.meta

Added new script to consume danger level and set the slider level in the UI to match the progression.

Danger Level Slider

---

Assets/Prefabs/UI/GameUI.prefab
Assets/Scenes/Immutable/TrueScene.unity
Assets/Scripts/Guns/PlayerGuns/PinkMist.cs
Assets/Scripts/Player/PlayerHealth.cs
Assets/Scripts/UI/GameplayUI.cs

Health Bar UI is hooked up to player health change event. Bug fixes for health resetting and pink mist trigger.

Health Bar UI

---

Assets/Code/Scripts/Audio/DualAudioEmitter.cs
Assets/Code/Scripts/Audio/DualRadioEmitter.cs
Assets/Code/Scripts/UI/TransmissionRadio.cs
Assets/EditorObject/WaveSequences/DrivingSynth/WastelandSoulWave1.asset
Assets/EditorObject/WaveSequences/DrivingSynth/WastelandSoulWave2.asset
Assets/EditorObject/WaveSequences/DrivingSynth/WastelandSoulWave3.asset
Assets/EditorObject/WaveSequences/DrivingSynth/WastelandSoulWave4.asset
Assets/EditorObject/WaveSequences/DrivingSynth/WastelandSoulWave5.asset
Assets/EditorObject/WaveSequences/DrivingSynth/WastelandSoulWave6.asset
Assets/EditorObject/WaveSequences/DrivingSynth/WastelandSoulWave7Complete.asset
Assets/Prefabs/UI/GameUI.prefab
Assets/Scenes/Immutable/TrueScene.unity

Delete Key now toggles the radio (mutes/unmutes) if player is inside transmission area.

Toggles radio with delete key, unless out of bounds; Wave DL changes

---

Assets/Code/Scripts/Audio/Jukebox.cs
Assets/Code/Scripts/SceneManageMent/Waves/AudioWave.cs
Assets/Code/Scripts/SceneManageMent/Waves/HostileWave.cs
Assets/Code/Scripts/SceneManageMent/Waves/LevelCompleteWave.cs
Assets/Code/Scripts/SceneManageMent/Waves/WaveSequence.cs
Assets/Code/Scripts/UI/GameplayUI.cs

Light refactors including logic moving, comments, and formatting.

Wave and Radio Refactors

---

Assets/Code/Scripts/Audio/Jukebox.cs
Assets/Code/Scripts/SceneManageMent/Waves/WaveSequence.cs
Assets/Code/Scripts/Utilities/LevelManager.cs

Some light revisions to wave sequence, comments, private variables, renaming, etc.

Small refactor to wave sequence

---

Assets/Code/Scripts/Audio/DualAudioEmitter.cs
Assets/Code/Scripts/Audio/DualRadioEmitter.cs
Assets/Code/Scripts/Audio/Jukebox.cs

Added comments, getter/setter for volume (to be used later), and a playerDead state handler.

Jukebox Small Refactoring

---

Assets/Code/Scripts/SceneManageMent/GameSettings.asset
Assets/Code/Scripts/SceneManageMent/GameSettings.asset.meta
Assets/Code/Scripts/SceneManageMent/MainMenu.cs
Assets/Code/Scripts/SceneManageMent/SettingsData.cs
Assets/Code/Scripts/SceneManageMent/SettingsData.cs.meta
Assets/Code/Scripts/UI/Settings.cs
Assets/Code/Scripts/UI/Settings.cs.meta
Assets/Code/Scripts/UI/StartGame.cs
Assets/Prefabs/Audio/JukeBox.prefab
Assets/Prefabs/UI/GameUI.prefab
Assets/Scenes/Immutable/MainMenu.unity
Assets/Scenes/Immutable/TrueScene.unity
Assets/Scenes/MasterMixer.mixer
Assets/Scenes/MasterMixer.mixer.meta

- Added sliders to control audio channels in the new audio mixer
- Added dropdown to control resolution, options are populated based on your system
- Added toggle box to toggle between fullscreen, set naturally based off if you launched the app with fullscreen on or off

Settings Menu Functionality

---

Assets/Code/Scripts/SceneManageMent/MainMenu.cs
Assets/Code/Scripts/UI/LevelSelector.cs
Assets/Code/Scripts/UI/LevelSelector.cs.meta
Assets/Code/Scripts/Utilities/LevelManager.cs
Assets/EditorObject/Levels/WastelandSoul Version 2.asset
Assets/EditorObject/Levels/WastelandSoul Version 2.asset.meta
Assets/Scenes/Immutable/MainMenu.unity

Level Selector class/object created, main menu start button sends level info to selector => level manager reads in from selector.

Level Selector

---

Assets/Code/Scripts/EditorObject/GameLevel.cs
Assets/Code/Scripts/UI/LevelButton.cs
Assets/Code/Scripts/UI/LevelButton.cs.meta
Assets/Code/Scripts/UI/LevelSelector.cs
Assets/Code/Scripts/UI/QuitScreen.cs
Assets/Code/Scripts/UI/UIContentCarousel.cs
Assets/Code/Scripts/UI/UIContentCarousel.cs.meta
Assets/EditorObject/Levels/WastelandSoul.asset
Assets/Prefabs/UI/CarouselDot.prefab
Assets/Prefabs/UI/CarouselDot.prefab.meta
Assets/Prefabs/UI/LevelButton [Button].prefab
Assets/Prefabs/UI/LevelButton [Button].prefab.meta
Assets/Scenes/Immutable/MainMenu.unity

Carousel for level selecting, player can now click on 'next' and 'previous' buttons to navigate through a list of levels and select one to load the level, and transition to truescene.

Carousel Level Select

---

Assets/Code/Scripts/EditorObject/GameLevel.cs
Assets/Code/Scripts/EditorObject/GameSave.cs
Assets/Code/Scripts/EditorObject/GameSave.cs.meta
Assets/Code/Scripts/SceneManageMent/MainMenu.cs
Assets/Code/Scripts/UI/LevelButton.cs
Assets/Code/Scripts/UI/LevelCompleteScreen.cs
Assets/Code/Scripts/UI/MenuManager.cs
Assets/Code/Scripts/UI/UIContentCarousel.cs
Assets/Code/Scripts/Utilities/LevelManager.cs
Assets/EditorObject/Game.meta
Assets/EditorObject/Game/GameSave.asset
Assets/EditorObject/Game/GameSave.asset.meta
Assets/EditorObject/Levels/WastelandSoul Version 2.asset
Assets/Scenes/Immutable/MainMenu.unity
Assets/Scenes/Immutable/TrueScene.unity

- Level progress is saved upon beating a level
- Your current level continues from the last level you beat
- The game save progress can be reset via the main menu
- Carousel hides levels that are not unlocked yet

Game Saves
